# Generated by Django 3.0.3 on 2020-05-31 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0002_groupachievement"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="achievementrequirements", unique_together=None,
        ),
        migrations.RemoveField(
            model_name="achievementrequirements", name="achievement",
        ),
        migrations.RemoveField(
            model_name="achievementrequirements", name="requirement",
        ),
        migrations.DeleteModel(name="GroupAchievement",),
        migrations.RemoveField(model_name="achievement", name="requirements",),
        migrations.DeleteModel(name="AchievementRequirements",),
    ]
