# Generated by Django 3.0.3 on 2020-05-31 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0020_auto_20200313_2240"),
        ("achievements", "0003_auto_20200531_0118"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="points",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="characters.Character",
                    ),
                ),
                (
                    "road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="achievements.Road",
                    ),
                ),
            ],
        ),
    ]
