# Generated by Django 3.0.3 on 2020-05-31 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0004_auto_20200531_0134"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievement", old_name="icon", new_name="icon_principal",
        ),
        migrations.RemoveField(model_name="achievement", name="roads",),
        migrations.AddField(
            model_name="achievement",
            name="icon_secondary",
            field=models.ImageField(default="", upload_to="achievements"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="achievement",
            name="road",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="achievements.Road",
            ),
            preserve_default=False,
        ),
    ]
