# Generated by Django 2.2.4 on 2019-08-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nick', models.CharField(max_length=128, unique=True)),
                ('user', models.CharField(blank=True, max_length=128, null=True)),
                ('characteristics', models.TextField()),
                ('job', models.CharField(blank=True, max_length=256, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('patronus', models.TextField()),
                ('wand', models.TextField()),
                ('secondary_characters', models.URLField()),
            ],
        ),
    ]
