# Generated by Django 2.2.4 on 2019-08-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='range',
            field=models.CharField(choices=[('1', 'Initie'), ('2', 'Legionario'), ('3', 'Templario'), ('4', 'Knight'), ('5', 'Demon Hunter'), ('6', 'Líder')], default='1', max_length=1),
        ),
    ]
