# Generated by Django 2.2.4 on 2019-09-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20190908_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_card',
            field=models.URLField(verbose_name='Link a la Ficha de Personaje'),
        ),
        migrations.AlterField(
            model_name='character',
            name='characteristics',
            field=models.TextField(verbose_name='Características Principales del Personaje'),
        ),
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Trabajo en el CMI'),
        ),
        migrations.AlterField(
            model_name='character',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='Información adicional sobre el trabajo'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nombre del Personaje'),
        ),
        migrations.AlterField(
            model_name='character',
            name='nick',
            field=models.CharField(max_length=128, unique=True, verbose_name='Nick de Usuario'),
        ),
        migrations.AlterField(
            model_name='character',
            name='patronus',
            field=models.TextField(verbose_name='Descripción del Patronus'),
        ),
        migrations.AlterField(
            model_name='character',
            name='range',
            field=models.CharField(choices=[('1', 'Initie'), ('2', 'Legionario'), ('3', 'Templario'), ('4', 'Knight'), ('5', 'Demon Hunter'), ('6', 'Líder')], default='1', max_length=1, verbose_name='Rango en el Bando'),
        ),
        migrations.AlterField(
            model_name='character',
            name='secondary_characters',
            field=models.URLField(blank=True, null=True, verbose_name='Link a las Fichas de los Personajes Secundario'),
        ),
        migrations.AlterField(
            model_name='character',
            name='storage_vault',
            field=models.URLField(verbose_name='Link a la Bóveda Trastero'),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre Real'),
        ),
        migrations.AlterField(
            model_name='character',
            name='vault',
            field=models.URLField(verbose_name='Link a la Bóveda'),
        ),
        migrations.AlterField(
            model_name='character',
            name='wand',
            field=models.TextField(verbose_name='Descripción de la Varita Mágica'),
        ),
    ]
