# Generated by Django 2.2.4 on 2019-09-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_character_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='business',
            field=models.ManyToManyField(blank=True, related_name='characters', to='business.Business'),
        ),
    ]
