# Generated by Django 3.0.3 on 2020-02-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0014_auto_20200215_2153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="user",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Nombre Real"
            ),
        ),
    ]
