# Generated by Django 2.2.4 on 2019-08-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20190816_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='range',
            field=models.CharField(choices=[('1', 'Initie'), ('2', 'Legionario'), ('3', 'Templario'), ('4', 'Knight'), ('5', 'Demon Hunter'), ('5', 'Líder')], default='1', max_length=1),
        ),
    ]
