# Generated by Django 2.2.4 on 2019-08-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
