# Generated by Django 2.2.4 on 2019-09-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20190825_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
