# Generated by Django 2.2.4 on 2019-09-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_character_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_card',
            field=models.URLField(default='http://www.harrylatino.org/topic/112868-plantilla-inscripcion-de-la-ocupacion-o-empleo-magico/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.jpg', upload_to='avatar/'),
        ),
    ]
