# Generated by Django 2.2.4 on 2019-09-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20190908_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='storage_vault',
            field=models.URLField(default='http://www.harrylatino.org/topic/112979-censo-de-personajes-odf/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='vault',
            field=models.URLField(default='http://www.harrylatino.org/topic/112979-censo-de-personajes-odf/'),
            preserve_default=False,
        ),
    ]
