# Generated by Django 2.2.4 on 2019-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_auto_20190912_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_lieutenant',
            field=models.BooleanField(default=False),
        ),
    ]
