# Generated by Django 3.0.3 on 2020-02-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0015_auto_20200215_2155"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
