# Generated by Django 3.0.3 on 2020-02-26 02:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0016_character_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character", options={"ordering": ("nick",)},
        ),
        migrations.AlterField(
            model_name="character",
            name="characteristics",
            field=ckeditor.fields.RichTextField(
                verbose_name="Características Principales del Personaje"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="job_description",
            field=ckeditor.fields.RichTextField(
                blank=True,
                null=True,
                verbose_name="Información adicional sobre el trabajo",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="patronus",
            field=ckeditor.fields.RichTextField(
                verbose_name="Descripción del Patronus"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="wand",
            field=ckeditor.fields.RichTextField(
                verbose_name="Descripción de la Varita Mágica"
            ),
        ),
    ]
