# Generated by Django 3.0.3 on 2020-03-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
        ("characters", "0017_auto_20200226_0210"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="achievements",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="characters",
                to="achievements.Achievement",
            ),
        ),
    ]
