# Generated by Django 3.0.3 on 2020-03-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0018_character_achievements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="slug",
            field=models.SlugField(editable=False, max_length=140),
        ),
    ]
