# Generated by Django 3.0.3 on 2020-05-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0006_point_reason"),
        ("characters", "0020_auto_20200313_2240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="achievements",
            field=models.ManyToManyField(
                blank=True, related_name="characters", to="achievements.Achievement"
            ),
        ),
    ]
