# Generated by Django 3.0.2 on 2020-01-26 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("characters", "0013_auto_20190913_0939"),
        ("awards", "0007_auto_20200113_0507"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="nick",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="max_options",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="voting",
            name="selected_options",
            field=models.ManyToManyField(to="characters.Character"),
        ),
        migrations.AlterField(
            model_name="voting",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="voting", unique_together={("user", "category")},
        ),
        migrations.RemoveField(model_name="voting", name="selected_option",),
    ]
