# Generated by Django 3.0.2 on 2020-02-13 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("characters", "0013_auto_20190913_0939"),
        ("awards", "0008_auto_20200126_1619"),
    ]

    operations = [
        migrations.RemoveField(model_name="accesstoken", name="nick",),
        migrations.AddField(
            model_name="accesstoken",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="voting",
            name="selected_options",
            field=models.ManyToManyField(
                to="characters.Character", verbose_name="Seleccionar las opciones"
            ),
        ),
    ]
