# Generated by Django 3.0.3 on 2020-02-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0015_auto_20200215_2155"),
        ("awards", "0011_category_self_voting"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="character",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="characters.Character",
            ),
        ),
    ]
