# Generated by Django 3.0.3 on 2020-02-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0013_auto_20200215_2203"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"ordering": ("order", "id")},
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
