# Generated by Django 3.0.3 on 2020-02-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0014_auto_20200219_1403"),
    ]

    operations = [
        migrations.AddField(
            model_name="award", name="opened", field=models.BooleanField(default=False),
        ),
    ]
