# Generated by Django 3.0.3 on 2020-03-01 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0017_auto_20200226_0210"),
        ("awards", "0015_award_opened"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="number_of_winners",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Winner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_votes", models.PositiveIntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="awards.Category",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="characters.Character",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="winners",
            field=models.ManyToManyField(
                related_name="winners",
                through="awards.Winner",
                to="characters.Character",
            ),
        ),
    ]
