# Generated by Django 3.0.3 on 2020-03-01 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0016_auto_20200301_2117"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="duplicate_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="awards.Award",
            ),
        ),
    ]
