# Generated by Django 3.0.3 on 2020-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0019_auto_20200318_0131"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="show_winners",
            field=models.BooleanField(default=False),
        ),
    ]
