# Generated by Django 2.2.5 on 2019-09-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('1', 'ALOJAMIENTO Y TURISMO'), ('2', 'ANIMALES Y PLANTAS DE JARDÍN'), ('3', 'CUIDADO PERSONAL, MODA Y COMPLEMENTOS'), ('4', 'CULTURA, DECORACIÓN, EXPOSICIÓN Y VENTA DE OBRAS ARTÍSTICAS'), ('5', 'DEPORTES'), ('6', 'DIVERSIÓN Y ENTRETENIMIENTO'), ('7', 'HOSTELERÍA'), ('8', 'ORGANIZACIÓN DE FIESTAS Y EVENTOS'), ('9', 'MISCELÁNEOS')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='header',
            field=models.ImageField(blank=True, default='header/default.jpg', upload_to='header/'),
        ),
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(default='slug', max_length=140),
            preserve_default=False,
        ),
    ]
