# Generated by Django 2.2.4 on 2019-09-15 22:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190909_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
