# Generated by Django 3.0 on 2020-01-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="slug",
            field=models.SlugField(editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, max_length=512),
        ),
    ]
