# Generated by Django 3.0 on 2020-01-12 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0003_auto_20200112_1915"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="award",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="awards.Award",
            ),
            preserve_default=False,
        ),
    ]
