# Generated by Django 3.0 on 2020-01-12 19:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0013_auto_20190913_0939"),
        ("awards", "0004_category_award"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="participants",
            field=models.ManyToManyField(
                related_name="categories", to="characters.Character"
            ),
        ),
        migrations.AddField(
            model_name="voting",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="votes",
                to="awards.Category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voting",
            name="selected_option",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="characters.Character",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voting",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="awards.AccessToken",
            ),
            preserve_default=False,
        ),
    ]
