# Generated by Django 3.0 on 2020-01-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0013_auto_20190913_0939"),
        ("awards", "0005_auto_20200112_1930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="categories",
                to="characters.Character",
            ),
        ),
    ]
