# Generated by Django 3.0 on 2020-01-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0013_auto_20190913_0939"),
        ("awards", "0006_auto_20200113_0445"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="characters.Character"
            ),
        ),
    ]
